# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_prolog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PathGUI import ROOT_DIR

from prolog import ask_KB,new_kb

class Ui_Dialog_prolog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(716, 594)
        self.insertText = QtWidgets.QPlainTextEdit(Dialog)
        self.insertText.setGeometry(QtCore.QRect(70, 520, 481, 51))
        self.insertText.setObjectName("insertText")
        self.askLabel = QtWidgets.QLabel(Dialog)
        self.askLabel.setGeometry(QtCore.QRect(10, 530, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.askLabel.setFont(font)
        self.askLabel.setObjectName("askLabel")
        self.viewResult = QtWidgets.QPlainTextEdit(Dialog)
        self.viewResult.setGeometry(QtCore.QRect(60, 50, 581, 451))
        self.viewResult.setObjectName("viewResult")
        self.viewResult.setReadOnly(True)
        self.buttonSend = QtWidgets.QPushButton(Dialog)
        self.buttonSend.setGeometry(QtCore.QRect(560, 520, 71, 51))
        self.buttonSend.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(ROOT_DIR+"\\utilities\\send.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonSend.setIcon(icon)
        self.buttonSend.setObjectName("buttonSend")
        self.buttonHelp = QtWidgets.QPushButton(Dialog)
        self.buttonHelp.setGeometry(QtCore.QRect(640, 520, 61, 51))
        self.buttonHelp.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(ROOT_DIR+"\\utilities\\question.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonHelp.setIcon(icon1)
        self.buttonHelp.setObjectName("buttonHelp")
        self.clearButton = QtWidgets.QPushButton(Dialog)
        self.clearButton.setGeometry(QtCore.QRect(600, 10, 41, 41))
        self.clearButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(ROOT_DIR+"\\utilities\\eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearButton.setIcon(icon2)
        self.clearButton.setObjectName("clearButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.buttonSend.clicked.connect(self.ask)
        self.clearButton.clicked.connect(self.clear)
        self.buttonHelp.clicked.connect(self.help)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Interrogazione sistema"))
        self.askLabel.setText(_translate("Dialog", "ASK"))

    def ask(self):
        cursor = QtGui.QTextCursor(self.viewResult.document())  # set the cursor position to 0
        cursor.setPosition(0)
        self.viewResult.setTextCursor(cursor)
        query = self.insertText.toPlainText()
        self.insertText.clear()
        font = QtGui.QFont()
        font.setPointSize(10)
        self.viewResult.setFont(font)
        cursor.setPosition(0)
        self.viewResult.setTextCursor(cursor)
        self.viewResult.insertPlainText("INPUT:\n" + query)
        self.viewResult.insertPlainText("\n\n OUTPUT:\n")
        result=ask_KB(new_kb,query)
        for r in result:
            self.viewResult.insertPlainText(r+"\n")
        self.viewResult.insertPlainText(".........................................................\n")
        cursor.setPosition(0)
        self.viewResult.setTextCursor(cursor)

    def clear(self):
        self.viewResult.clear()

    def help(self):
        msg_box = QMessageBox()
        msg_box.setIcon(QMessageBox.Information)
        msg_box.setWindowTitle("Help")
        msg_box.setText("Esempio query:\n"
                        "- fermata(Idfermata,Nomefermata)\n"
                        "- orario_feriale(Idfermata,Hprimacorsa,Hultimacorsa)\n"
                        "- orario_festivo(Idfermata,Hprimacorsa,Hultimacorsa)\n"
                        "- pedana_disabili(Idpullman,Si/no)\n"
                        "- compra_biglietto_sul_bus(Idpullman,Si/no)\n"
                        "- tabella_fermata_feriale(IdFermata,Nomefermata,Hprima corsa,Hultimacorsa)\n"
                        "- tabella_fermata_festiva(IdFermata,Nomefermata,Hprima corsa,Hultimacorsa)\n")
        msg_box.setStandardButtons(QMessageBox.Ok)
        retval = msg_box.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog_prolog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
